apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: demo-game-mw
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /gameku
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-game-ingress
  labels:
    app: demo-game
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: default-demo-game-mw@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /gameku
        pathType: Prefix
        backend:
          service:
            name: demo-game-service
            port:
              number: 80