apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    app: nginx-app
spec:
  rules:
  - http:
      paths:
      - path: /websiteku
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80