apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-nginx
  name: simple-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80